package com.example.file_management.entity;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

@Getter
@Setter
public class FileVersion {
    private Long id;
    //for未创建的文档，fileId可能为空
    private Integer fileId;
    //文件内递增：v1, v2, ...
    private int versionNo;
    private String title;
    private String content;
    private int editorId;
    //版本开启时间
    private Date openTime;
    //最近一次合并进此版本的时间，窗口判定用它
    private Date lastMergeTime;

    //default title is idempotency key generated by repository
    // + tenantId + 用户点击创建时前端记录的时间戳
    //不管标题怎么变，都能通过这个idempotency key to trace all file versions
    //为了以后扩展可回滚的功能
    private String defaultTitle;

    private int tenantId;
    private int repositoryId;

    public FileVersion() {
    }
}
